/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GameBoard: typeof import('./components/GameBoard.vue')['default']
    GameController: typeof import('./components/GameController.vue')['default']
    GameEntryDialog: typeof import('./components/GameEntryDialog.vue')['default']
    GameEntryUsersDialog: typeof import('./components/GameEntryUsersDialog.vue')['default']
    GameHowToDialog: typeof import('./components/GameHowToDialog.vue')['default']
    GameInformation: typeof import('./components/GameInformation.vue')['default']
    GameMatchTitle: typeof import('./components/GameMatchTitle.vue')['default']
    GameRoomListDialog: typeof import('./components/GameRoomListDialog.vue')['default']
    GameSplash: typeof import('./components/GameSplash.vue')['default']
    GameSquare: typeof import('./components/GameSquare.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
